# Generated by Django 3.1.4 on 2020-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school_timetable',
            fields=[
                ('userID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('data', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
    ]
