# Generated by Django 3.1.4 on 2020-12-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomApply',
            fields=[
                ('applyID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('classroomID', models.CharField(max_length=20)),
                ('timePeriod', models.CharField(choices=[(0, '第一，二节课'), (1, '第三、四节课'), (2, '第五、六节课'), (3, '第七、八节课'), (4, '第九节课之后')], max_length=50)),
                ('userID', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(0, '批准'), (1, '未受理'), (2, '拒绝')], max_length=30)),
                ('reason', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('classroomID', models.CharField(max_length=20)),
                ('timePeriod', models.CharField(choices=[(0, '第一，二节课'), (1, '第三、四节课'), (2, '第五、六节课'), (3, '第七、八节课'), (4, '第九节课之后')], max_length=50)),
                ('status', models.CharField(choices=[(0, '空闲'), (1, '有课'), (2, '有条'), (3, '借出'), (4, '可拼')], default='空闲', max_length=30)),
                ('applyID', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='申请时间',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='申请理由',
        ),
        migrations.DeleteModel(
            name='select',
        ),
        migrations.DeleteModel(
            name='order_select1',
        ),
        migrations.DeleteModel(
            name='order_select2',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
