# Generated by Django 3.1.4 on 2020-12-15 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercls', '0003_auto_20201215_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomstatus',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 15)),
        ),
    ]
