# Generated by Django 3.1.4 on 2020-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercls', '0005_auto_20201215_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomapply',
            name='applyID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
